from typing import Any, Dict, List, Optional, Union

class Server:
    def emit(self, event: str, data: Any, room: Any, namespace: Any) -> None: ...
    def send(self, data: Any, room: Any, namespace: Any) -> None: ...

class AsyncServer:
    def emit(self, event: str, data: Any, room: Any, namespace: Any) -> None: ...
    def send(self, data: Any, room: Any, namespace: Any) -> None: ...